apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: development
spec:
  type: NodePort
  selector:
    app: ssh
  ports:
    # the port that this service should serve on
  - port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 31098
