apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
    nodePort: 31886
  selector:
    app: redis
    role: master
